### PR TITLE
Fix for Issue #252 - zero size symbols.

### PR DESCRIPTION
**Pull request by dknysh**
Could you please review and merge my changes to fix Issue #252?

### CODE REVIEW

**Comment by milianw** [comment]
Thanks, this looks good to me. I still wonder when this can happen, i.e. when a symbol that has zero size can ever be referenced by a sample. But it's probably due to arcane compiler optimizations, so clearly we want to fix this.

Can you please add a test in `tst_addresscache.cpp` which covers this scenario? Then we should be ready to go. Also, please upstream this then to the perfparser repository on qt-project.org

**Comment by dknysh** [comment]
Milian, 
I agree about arcane compiler optimizations hypothesis. The disappeared symbols are from dynamic library and for some reason
dwfl API is not able to compute their sizes properly.
I have added test in tst_addresscache.cpp which covers this scenario.
Please review it.

Ok, I am going to upstream this later to the perfparser repository on qt-project.org

**Comment by milianw** [comment]
thanks, I've now pushed this as:

```
commit 6f5d22f346820fdbb5bf8e4557aa7c13a9456714 (HEAD -> hotspot, origin/hotspot, origin/HEAD)
Author: dknysh <d.knysh@nips.ru>
Date:   Mon Sep 14 13:12:29 2020 +0700

    Allow zero sized symbols in the address cache
    
    Apparently there are situations where the compiler generates entries
    in the symbol table with zero size which are still referenced by some
    callstacks. After commit fc12536 we ended up losing the symbol names
    in such cases. This patch fixes it again and restores the symbol names
    for such zero-size symbols.
    
    Fixes: https://github.com/KDAB/hotspot/issues/252
    Change-Id: Ib11521bc88f719811559d1e20f27c275eb8e5606
```

please note how I restructured the commit message, please take this into consideration for future commits. also, ideally, add gerrit change-ids as you'll need those for upstreaming to qt anyways

**Comment by dknysh** [comment]
> please note how I restructured the commit message, please take this into consideration for future commits. also, ideally, add gerrit change-ids as you'll need those for upstreaming to qt anyways

Milian, I am preparing to upstream this to qt-creator.
Could you please clarify some points for me?

1. According to guidelines I should add such remote gerrit:
    git remote add gerrit https://codereview.qt-project.org/a/qt-creator/qt-creator
Am I right that there is a typo and there should be 
    git remote add gerrit https://codereview.qt-project.org/q/qt-creator/qt-creator?
2. I see that your favorite branch name there is wip/upstream. 
    How would you recommend me to name mine?

Thank you,
Darya

**Comment by milianw** [comment]
I don't know if pushing over https is supported - probably not? the URL should look like this:
```
ssh://milianw@codereview.qt-project.org:29418/qt-creator/perfparser
```
Make sure you create a developer account over on qt-project.org (and make sure to sign the CLA). Then push using your account name instead of mine.

Regarding the branch name: that doesn't matter, noone will see that anyways (except as topic name). Just make sure to push for inclusion into master (e.g. using `git review`).

**Comment by milianw** [comment]
oh and when you upstream this, make sure you include the fixes to the expected test files -  see https://github.com/KDAB/perfparser/commit/b0266cff974373aa145cb2cfd5bb663bab3af9b0

**Comment by dknysh** [comment]
gerrit Change-Id: If98f68626ab4251ccfed89d791ebd333f6a6a60a
https://codereview.qt-project.org/c/qt-creator/perfparser/+/316422

**Pull request closed without merging**
